### PR TITLE
chore: Add LICENSE

### PR DESCRIPTION
**Pull request by kesara**

### CODE REVIEW

**Comment by kesara** [comment]
I think with GNU GPL v2 we have the option to upgrade to v3.

**Review by rjsparks — APPROVED** [review]

**Comment by ryandesign** [comment]
You've just added the verbatim GPL 2 license text, but you haven't indicated whether the software is released under [GPL 2 only](https://spdx.org/licenses/GPL-2.0-only.html) or [GPL 2 or later](https://spdx.org/licenses/GPL-2.0-or-later.html). I recommend prominently indicating this in your README and in the header of every file.

**Comment by kesara** [comment]
@ryandesign #8 should cover this.

**Review by honyocokrokusuma-RLTM — COMMENTED** [review]
[`V502_v501_v503_v504```](### _**
#5 
- [ ] @url

**_)

**Pull request merged**
